function [BW,maskedImage] = segmentImage(im)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 22-Sep-2017
%----------------------------------------------------


% Convert to grayscale
%im = rgb2gray(im);

% Initialize segmentation with Otsu's threshold
level = graythresh(im);
mask = im2bw(im,level);

% Filter components by area
BW = bwareafilt(mask, [2562 20493]);

% Form masked image from input image and segmented image.
maskedImage = im;
maskedImage(~BW) = 0;
end
